<a href="https://colab.research.google.com/github/ArpulaAnjali/B19_1319/blob/main/Lab2_problem1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
Marks=np.array([[96,56,80],[67,89,78],[90,67,56],[89,90,78],[67,45,34]])
print(Marks)

[[96 56 80]
 [67 89 78]
 [90 67 56]
 [89 90 78]
 [67 45 34]]


In [3]:
avg_marks = Marks.mean(axis=1)
min_marks = Marks.min(axis=1)
max_marks = Marks.max(axis=1)
print("\nAverage marks per student:", avg_marks)
print("Minimum marks per student:", min_marks)
print("Maximum marks per student:", max_marks)


Average marks per student: [77.33333333 78.         71.         85.66666667 48.66666667]
Minimum marks per student: [56 67 56 78 34]
Maximum marks per student: [96 89 90 90 67]


In [4]:
print("\nMarks of Students 2 to 4:\n", Marks[1:4])


Marks of Students 2 to 4:
 [[67 89 78]
 [90 67 56]
 [89 90 78]]


In [5]:
above_80 = Marks[(Marks > 80).all(axis=1)]
print("\nStudents scoring above 80 in all subjects:\n", above_80)


Students scoring above 80 in all subjects:
 []


In [6]:
reshaped = Marks.T
print("\nSubject-wise performance:\n", reshaped)


Subject-wise performance:
 [[96 67 90 89 67]
 [56 89 67 90 45]
 [80 78 56 78 34]]
