<a href="https://colab.research.google.com/github/ArpulaAnjali/B19_1319/blob/main/Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
fp=open("example.txt","w")
fp.write("Hello,B.Tech students!\n")
fp.write("sR university\n")
fp.write("suresh kumar")
fp.close()
print("Data written successfully!")

Data written successfully!


In [5]:
file=open("example.txt","r")
content=file.read()
print("file Content:\n",content)
file.close()


file Content:
 Hello,B.Tech students!
sR university
suresh kumar


In [9]:
file=open("example.txt","r")
l1=file.readline()
print("First Line:",l1)
l2=file.readline()
print("Second Line:",l2)
lines=file.readlines()
print("All lines:",lines)
file.close()

First Line: Hello,B.Tech students!

Second Line: sR university

All lines: ['suresh kumarappending new data..\n', 'appending new data..\n']


In [8]:
#appending data to an existing file
file=open("example.txt","a")
file.write("appending new data..\n")
file.close()

In [10]:
with open("example.txt","r") as fp:
  data=fp.read()
  print(data)

Hello,B.Tech students!
sR university
suresh kumarappending new data..
appending new data..



In [14]:
import csv
with open("data.csv","w",newline='') as fp:
  wr=csv.writer(fp)
  wr.writerows([["Name","Age","Course"],["aaa",21,"CSE"],["bbb",20,"ECE"]])
with open("data.csv","r") as file:
    re=csv.reader(file)
    for row in re:
      print(row)


['Name', 'Age', 'Course']
['aaa', '21', 'CSE']
['bbb', '20', 'ECE']


In [17]:
import numpy as np
arr1=np.array([1,2,3,4])
print("1D Array:",arr1)

1D Array: [1 2 3 4]


In [18]:
arr2=np.array([[1,2,3],[4,5,6]])
print("2D Array:\n",arr2)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [19]:
zeros_arr=np.zeros((3,3))
print("Zeros Array:\n",zeros_arr)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
ones_arr=np.ones((2,4))
print("Ones Array:\n",ones_arr)

Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape:",arr.shape)#(rows,columns)
print("dimension:",arr.ndim)#2D Array
print("data type:",arr.dtype)#int64 or float64
print("Size:",arr.size)#total elements
print("item size:",arr.itemsize)#bytes per element

Shape: (2, 3)
dimension: 2
data type: int64
Size: 6
item size: 8


In [28]:
a=np.array([10,20,30,40,50])
print("first element:",a[0])
print("last element:",a[-1])
print("slice[1:4]:",a[1:4])
print("every second element:",a[::2])

first element: 10
last element: 50
slice[1:4]: [20 30 40]
every second element: [10 30 50]


In [27]:
#2D indexing
arr2=np.array([[1,2,3],[4,5,6]])
print("element at r1 col 2:",arr2[0,1])
print("second row",arr2[1,:])
print("second column:",arr2[:,1])

element at r1 col 2: 2
second row [4 5 6]
second column: [2 5]


In [33]:
a = np.array([1, 2, 3])
b = 5
print("Add scalar to array:", a + b)  # [6 7 8]

c = np.array([[1], [2], [3]])
d = np.array([4, 5, 6])
print("Broadcasted sum:\n",c+d)

Add scalar to array: [6 7 8]
Broadcasted sum:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [31]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix Multiplication:\n", np.dot(A, B))
print("Transpose:\n", A.T)
print("Inverse:\n", np.linalg.inv(A))
print("Determinant:", np.linalg.det(A))

Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004


In [30]:
import numpy as np

# Marks of students in 3 subjects
marks = np.array([
    [85, 90, 88],
    [78, 81, 85],
    [92, 89, 95]
])

print("Average marks per student:", np.mean(marks, axis=1))
print("Average marks per subject:", np.mean(marks, axis=0))
print("Highest marks in each subject:", np.max(marks, axis=0))
print("Lowest marks in each subject:", np.min(marks,axis=0))

Average marks per student: [87.66666667 81.33333333 92.        ]
Average marks per subject: [85.         86.66666667 89.33333333]
Highest marks in each subject: [92 90 95]
Lowest marks in each subject: [78 81 85]
